### PR TITLE
chore: Initial commit

### PR DESCRIPTION
**Pull request by jaxparrow07**
Added Dark Mode for CZFileManager

image

### CODE REVIEW

**Comment by axonasif** [comment]
Why is the commit message `chore: Initial commit`? It doesn't make sense since you actually updated the CZ-FM apk for implementing the dark mode style. Your commit message for example could be: `feat: Implement dark interface style in cz-filemanager`.

If you want to fix this then do the following in your local machine git repository:
```bash
git commit --amend # Change the message
git push -f
```

**Comment by jaxparrow07** [comment]
Changed commit

**Review by hmtheboy154 — CHANGES_REQUESTED** [review]
@axonasif put it in dminit, not here

**Comment by axonasif** [comment]
> 
> 
> @axonasif put it in dminit, not here

Oh right, I forgot that part.
@jaxparrow07 Please swap this file with `PHOENIXOS_LFM.apk` at [here](https://github.com/bigdroid-hooks/custom_ghome/tree/main/ghome/dependencies/assets/user-apps)

Note: Make sure to commit in `darkmatter` branch.
Do `git checkout darkmatter` after cloning and then push.

**Review by axonasif — COMMENTED** [review]
> Requested change approved.

**Comment by jaxparrow07** [comment]
Done

**Pull request closed without merging**
